version: '3'
services:
  chat_server:
    build:
      context: ./backend/chat_server
      dockerfile: Dockerfile
    ports:
      - '2053:2053'
    volumes:
      - ./backend/chat_server:/app

  node_websockets:
    build:
      context: ./backend/node_websockets
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./backend/node_websockets:/app

  flask_api:
    build:
      context: ./backend/flask_api
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    volumes:
      - ./backend/flask_api:/app